development:
  domain: localhost.doxsite.com
  www_domain: www.localhost.doxsite.com:3000
  email_domain: localhost.mydoxsite.com
  key: "AuW3fclBSB0yMloWXEB6uKDwa4FembERFCx7gy5t"
  secret: "wLUfsNAjHntWUQZNpobhIzhcQWQXoMqgsehcfTeQ"
    
production:
  domain: dev.doxsite.com
  www_domain: www.dev.doxsite.com
  email_domain: dev.mydoxsite.com
  key: "anqfyptwWzSlNjZmrU4jt2nei03FOJJv9yTUoSxB"
  secret: "RAOIyQIDWkbaqJzPiObYDCMoxCNDc1BiC8m2mxOu"